#![feature(test)]

extern crate test;

use games::{gamerules::GameRules, pijersi::PijersiPosition};

fn run_perft() {
    let fens: [&str; 186] = [
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/1PRS-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/PR1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/PRS-R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/1S-R-WWS-R-P-/PRP-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/PR5/1S-R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/1PR5/6/1S-R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-SRR-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-1R-WWS-R-P-/SRP-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/SR5/P-1R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1SR4/P-1R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/SR6/6/P-1R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2SR4/6/P-1R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-SR1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-1SRP-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-1PRS- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-PR1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWSRR-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WW1R-P-/R-P-S-SRP-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3SR2/P-S-R-WW1R-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4SR1/P-S-R-WW1R-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3SR3/6/P-S-R-WW1R-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/5SR1/6/P-S-R-WW1R-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1R-4/P-S-1WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2R-3/P-S-1WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-1WWS-R-P-/R-PRS-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-PRWWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2PR3/P-S-1WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-1WWS-R-P-/R-P-SRR-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-SRWWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1SR4/P-S-1WWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-SR1WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-1SRWWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/SR5/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1SR4/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/SR6/6/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2SR4/6/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4R-1/P-S-R-WWS-1P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5R-/P-S-R-WWS-1P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-1P-/R-P-S-R-PRS- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-PRP-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5PR/P-S-R-WWS-1P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-1P-/R-P-S-R-P-SR b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-SRP-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4SR1/P-S-R-WWS-1P-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWSR1P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WW1SRP-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3SR2/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4SR1/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3SR3/6/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/5SR1/6/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-1PR/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-PR1/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5PR/P-S-R-WWS-2/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/5PR1/6/P-S-R-WWS-2/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/RP1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/1RPS-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-1SPR-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-SP1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-SPR-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-1R-WWS-R-P-/R-SPS-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/SP5/P-1R-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1SP4/P-1R-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/SP6/6/P-1R-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2SP4/6/P-1R-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-RPWWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-1WWS-R-P-/R-RPS-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1RP4/P-S-1WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2RP3/P-S-1WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/1RP5/6/P-S-1WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3RP3/6/P-S-1WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-RP1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-1RPS- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-R-1SP b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-R-SP1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWSPR-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WW1R-P-/R-P-S-R-SPS- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3SP2/P-S-R-WW1R-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4SP1/P-S-R-WW1R-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3SP3/6/P-S-R-WW1R-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/5SP1/6/P-S-R-WW1R-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-RPP-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-1P-/R-P-S-R-RPS- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4RP1/P-S-R-WWS-1P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5RP/P-S-R-WWS-1P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4RP2/6/P-S-R-WWS-1P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/6RP/6/P-S-R-WWS-1P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/P-5/1S-R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/1S-R-WWS-R-P-/RPP-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/RPS-R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/1SPR-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/SP1R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/SP5/2R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1SP4/2R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/SP6/6/2R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2SP4/6/2R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5P-/P-S-R-WWS-R-1/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-1/R-P-S-R-P-SP b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-SP/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-RP1/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-1RP/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4RP1/P-S-R-WWS-2/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5RP/P-S-R-WWS-2/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4RP2/6/P-S-R-WWS-2/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/6RP/6/P-S-R-WWS-2/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-PS1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-1PSR-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-1RSP-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-RS1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-RSWWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-1WWS-R-P-/R-P-RSR-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1RS4/P-S-1WWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2RS3/P-S-1WWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/1RS5/6/P-S-1WWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3RS3/6/P-S-1WWS-R-P-/R-P-1R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-R-PS1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-P-/R-P-S-R-1PS b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-RSP-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-1P-/R-P-S-R-P-RS b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4RS1/P-S-R-WWS-1P-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5RS/P-S-R-WWS-1P-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4RS2/6/P-S-R-WWS-1P-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/6RS/6/P-S-R-WWS-1P-/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-PS/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWS-R-1/R-P-S-R-P-PS b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5PS/P-S-R-WWS-R-1/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/5PS1/6/P-S-R-WWS-R-1/R-P-S-R-P-1 b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/S-5/P-1R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1S-4/P-1R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-1R-WWS-R-P-/RSP-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-RSR-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1RS4/P-1R-WWS-R-P-/1P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-1R-WWS-R-P-/R-PSS-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-PSR-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/PS5/P-1R-WWS-R-P-/R-1S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/PS1R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/1PSR-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/PS5/2R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/1PS5/6/2R-WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-1RSWWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-RS1WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1RS4/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2RS3/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/1RS5/6/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3RS3/6/P-2WWS-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3S-2/P-S-R-WW1R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4S-1/P-S-R-WW1R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WW1R-P-/R-P-S-RSP-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWRSR-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4RS1/P-S-R-WW1R-P-/R-P-S-1P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WW1R-P-/R-P-S-R-PSS- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWPSR-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3PS2/P-S-R-WW1R-P-/R-P-S-R-1S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WW1RSP-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/6/P-S-R-WWRS1P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/4RS1/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/5RS/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4RS2/6/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/6RS/6/P-S-R-WW2P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2WW3/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3WW2/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2WW4/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4WW2/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2W-3/P-S-R-W-S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2W-3/P-S-R-W-S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/1W-W-3/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2W-W-2/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2W-4/2W-3/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3W-3/2W-3/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3W-2/P-S-R-W-S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3W-2/P-S-R-W-S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/2W-W-2/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/7/3W-W-1/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3W-3/3W-2/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4W-2/3W-2/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2W-4/1W-4/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2W-4/2W-3/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/1W-W-4/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/2W-W-3/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/1W-4/2W-4/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/2W-3/2W-4/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4W-2/3W-2/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4W-2/4W-1/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/3W-W-2/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/6/4W-W-1/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/3W-2/4W-2/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
        "s-p-r-s-p-r-/p-r-s-wwr-s-p-/4W-1/4W-2/6/P-S-R-1S-R-P-/R-P-S-R-P-S- b 0 1",
    ];

    for fen in fens {
        let mut pos = PijersiPosition::from_fen(fen);
        std::hint::black_box(pos.perft(2));
    }
}

#[cfg(test)]
mod pijersi {
    use super::*;
    use test::Bencher;

    #[bench]
    fn perft(b: &mut Bencher) {
        b.iter(|| run_perft());
    }
}
